# Generated by Django 6.0 on 2026-01-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="temp_user",
            field=models.BooleanField(
                default=False,
                help_text="If True users will be asked to login with a temporary user account. A link to the survey will be listed in the user profile bookmark list.",
                verbose_name="Temp User Survey",
            ),
        ),
    ]
