# Generated by Django 6.0 on 2026-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0002_survey_temp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="screensaver",
            field=models.BooleanField(
                default=False,
                help_text="If True a screensaver will be shown after time set in settings.",
                verbose_name="Show Screensaver",
            ),
        ),
    ]
