# Generated by Django 6.0 on 2026-01-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0003_survey_screensaver"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="screensaver",
            field=models.BooleanField(
                default=False,
                help_text="If True a screensaver will be shown after time set in settings.",
                verbose_name="Show Screensaver",
            ),
        ),
    ]
