# Generated by Django 6.0 on 2026-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0004_surveyselection_screensaver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type_field",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Text"),
                    (1, "Title"),
                    (2, "Number"),
                    (3, "Radio"),
                    (4, "Select"),
                    (5, "Multi Select"),
                    (6, "Text Area"),
                    (7, "URL"),
                    (8, "Email"),
                    (9, "Date"),
                    (10, "Rating"),
                ],
                verbose_name="type of input field",
            ),
        ),
    ]
