# Generated by Django 5.2.8 on 2025-12-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0018_survey_cycle_survey"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "slug",
                    models.SlugField(
                        default="", max_length=225, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "can_anonymous_user",
                    models.BooleanField(
                        default=False,
                        help_text="If True, user without authentatication can view.",
                        verbose_name="anonymous submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "survey selection",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name__length__gt", 0)),
                        name="non_empty_name_survey_selection",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="survey",
            name="survey_selection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="djf_surveys.surveyselection",
                verbose_name="survey selection",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="survey",
            order_with_respect_to="survey_selection",
        ),
    ]
