# Generated by Django 5.2.8 on 2025-12-09 17:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0019_surveyselection_survey_survey_selection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="success_page_content",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Success Page Content"
            ),
        ),
    ]
