# Generated by Django 5.2.7 on 2025-10-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0019_surveyselection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyselection",
            name="survey",
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="survey",
            field=models.ManyToManyField(
                to="djf_surveys.survey", verbose_name="survey"
            ),
        ),
    ]
