# Generated by Django 5.2.8 on 2025-12-09 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0020_surveyselection_success_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
