# Generated by Django 5.2.7 on 2025-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0020_remove_surveyselection_survey_surveyselection_survey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyselection",
            name="user",
        ),
    ]
