# Generated by Django 5.2.7 on 2025-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0021_remove_surveyselection_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="return_to_page",
            field=models.URLField(
                blank=True,
                help_text="Enter the URL to redirect after survey is completed.",
                null=True,
                verbose_name="Return to Page",
            ),
        ),
    ]
