# Generated by Django 5.2.8 on 2025-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0021_surveyselection_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="cancel_button",
            field=models.BooleanField(
                default=False,
                help_text="If True, a button to cancel the survey is displayed.",
                verbose_name="Show cancel button",
            ),
        ),
    ]
