# Generated by Django 5.2.7 on 2025-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0022_survey_return_to_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="return_to_page",
        ),
        migrations.AddField(
            model_name="survey",
            name="return_to_selection_page",
            field=models.URLField(
                blank=True,
                help_text="Enter the Survey Selection URL to redirect after survey is completed.",
                null=True,
                verbose_name="Return to Selection Page",
            ),
        ),
    ]
