# Generated by Django 5.2.8 on 2025-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0022_survey_cancel_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="gdpr_compliant",
            field=models.BooleanField(
                default=False,
                help_text="If True, the survey will include a unique identifier for GDPR compliance.",
                verbose_name="GDPR compliant",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="gdpr_reference",
            field=models.UUIDField(
                blank=True, default=None, null=True, verbose_name="GDPR reference"
            ),
        ),
    ]
