# Generated by Django 5.2.8 on 2025-12-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0023_survey_gdpr_compliant_survey_gdpr_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="gdpr_reference",
        ),
        migrations.AddField(
            model_name="useranswer",
            name="gdpr_reference",
            field=models.UUIDField(
                blank=True, default=None, null=True, verbose_name="GDPR reference"
            ),
        ),
    ]
