# Generated by Django 5.2.7 on 2025-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0023_remove_survey_return_to_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyselection",
            name="survey",
            field=models.ManyToManyField(
                related_name="survey_selections",
                to="djf_surveys.survey",
                verbose_name="survey",
            ),
        ),
    ]
