# Generated by Django 5.2.7 on 2025-10-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0023_remove_survey_return_to_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="return_to_selection_page",
        ),
    ]
