# Generated by Django 5.2.8 on 2025-12-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0024_remove_survey_gdpr_reference_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyselection",
            options={"ordering": ["-created_at"], "verbose_name": "survey selection"},
        ),
    ]
