# Generated by Django 5.2.8 on 2025-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0025_alter_surveyselection_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="show_on_index",
            field=models.BooleanField(
                default=True,
                help_text="If True, the survey will be listed on the index page.",
                verbose_name="Show on index page",
            ),
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="show_on_index",
            field=models.BooleanField(
                default=True,
                help_text="If True, the survey selection will be listed on the index page.",
                verbose_name="Show on index page",
            ),
        ),
    ]
