# Generated by Django 5.2.7 on 2025-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0025_remove_survey_return_to_selection_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="name",
            field=models.CharField(
                default="default value", max_length=200, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
