# Generated by Django 5.2.8 on 2025-12-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0026_survey_show_on_index_surveyselection_show_on_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="show_on_index",
            field=models.BooleanField(
                default=False,
                help_text="If True, the survey will be listed on the index page.",
                verbose_name="Show on index page",
            ),
        ),
        migrations.AlterField(
            model_name="surveyselection",
            name="show_on_index",
            field=models.BooleanField(
                default=False,
                help_text="If True, the survey selection will be listed on the index page.",
                verbose_name="Show on index page",
            ),
        ),
    ]
