# Generated by Django 5.2.7 on 2025-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0026_surveyselection_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="surveyselection",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__length__gt", 0)),
                name="non_empty_name_survey_selection",
            ),
        ),
    ]
