# Generated by Django 6.0 on 2025-12-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0027_alter_survey_show_on_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="show_fullscreen",
            field=models.BooleanField(
                default=False,
                help_text="Can be checked in app template for removal of header/navbar etc.",
                verbose_name="Remove app header/nav etc",
            ),
        ),
    ]
