# Generated by Django 5.2.7 on 2025-10-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0027_surveyselection_non_empty_name_survey_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="slug",
            field=models.SlugField(default="", max_length=225, verbose_name="slug"),
        ),
    ]
