# Generated by Django 5.2.7 on 2025-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0028_surveyselection_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyselection",
            name="slug",
            field=models.SlugField(
                default="", max_length=225, unique=True, verbose_name="slug"
            ),
        ),
    ]
