# Generated by Django 6.0 on 2025-12-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0028_survey_show_fullscreen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="show_fullscreen",
            field=models.BooleanField(
                default=False,
                help_text="Can be checked in app template for removal of header/navbar etc.",
                verbose_name="Show fullscreen",
            ),
        ),
    ]
