# Generated by Django 5.2.7 on 2025-11-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0029_alter_surveyselection_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyselection",
            old_name="survey",
            new_name="surveys",
        ),
    ]
