# Generated by Django 6.0 on 2025-12-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0030_surveyselection_show_fullscreen"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="private_survey",
            field=models.BooleanField(
                default=False,
                help_text="If True the survey will be listed only on home page for user when logged in.",
                verbose_name="Private Survey",
            ),
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="private_surveyselection",
            field=models.BooleanField(
                default=False,
                help_text="If True the survey will be listed only on home page for user when logged in.",
                verbose_name="Private Survey Selection",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="show_fullscreen",
            field=models.BooleanField(
                default=False,
                help_text="If True then header/navbar etc. is removed.",
                verbose_name="Show fullscreen",
            ),
        ),
    ]
