# Generated by Django 5.2.7 on 2025-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0030_rename_survey_surveyselection_surveys"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="description",
            field=models.TextField(default="", verbose_name="description"),
            preserve_default=False,
        ),
    ]
