# Generated by Django 5.2.7 on 2025-11-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0031_surveyselection_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyselection",
            name="surveys",
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="surveys",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="survey_selections",
                to="djf_surveys.survey",
                verbose_name="survey",
            ),
            preserve_default=False,
        ),
    ]
