# Generated by Django 6.0 on 2025-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0031_survey_private_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="bookmark_survey",
            field=models.BooleanField(
                default=False,
                help_text="If True a link to the survey will be listed in the user profile bookmark list.",
                verbose_name="Bookmark Survey",
            ),
        ),
        migrations.AddField(
            model_name="surveyselection",
            name="bookmark_surveyselection",
            field=models.BooleanField(
                default=False,
                help_text="If True a link to the survey selection will be listed in the user profile bookmark list.",
                verbose_name="Bookmark Survey Selection",
            ),
        ),
    ]
