# Generated by Django 6.0 on 2025-12-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0032_survey_bookmark_survey_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="bookmark_survey",
            new_name="bookmark",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="show_fullscreen",
            new_name="fullscreen",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="private_survey",
            new_name="private",
        ),
        migrations.RenameField(
            model_name="surveyselection",
            old_name="bookmark_surveyselection",
            new_name="bookmark",
        ),
        migrations.RenameField(
            model_name="surveyselection",
            old_name="show_fullscreen",
            new_name="fullscreen",
        ),
        migrations.RenameField(
            model_name="surveyselection",
            old_name="private_surveyselection",
            new_name="private",
        ),
    ]
