# Generated by Django 5.2.7 on 2025-11-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0034_alter_survey_survey_selections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_selections",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="surveys",
                to="djf_surveys.surveyselection",
                verbose_name="survey selection",
            ),
        ),
    ]
