# Generated by Django 6.0 on 2025-12-31 16:03

import django.db.models.deletion
import djf_surveys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0035_alter_survey_owner_alter_surveyselection_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="owner",
            field=models.ForeignKey(
                default=djf_surveys.models.get_default_owner,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="surveyselection",
            name="owner",
            field=models.ForeignKey(
                default=djf_surveys.models.get_default_owner,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
