# Generated by Django 5.2.7 on 2025-11-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0035_alter_survey_survey_selections"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyselection",
            name="can_anonymous_user",
            field=models.BooleanField(
                default=False,
                help_text="If True, user without authentatication can submit.",
                verbose_name="anonymous submission",
            ),
        ),
    ]
