# Generated by Django 5.2.7 on 2025-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0036_surveyselection_can_anonymous_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyselection",
            name="can_anonymous_user",
            field=models.BooleanField(
                default=False,
                help_text="If True, user without authentatication can view.",
                verbose_name="anonymous submission",
            ),
        ),
    ]
