# Generated by Django 5.2.8 on 2025-11-16 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0037_alter_surveyselection_can_anonymous_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_selections",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="djf_surveys.surveyselection",
                verbose_name="survey selection",
            ),
        ),
    ]
