# Generated by Django 5.2.8 on 2025-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0038_alter_survey_survey_selections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ["ordering"],
                "verbose_name": "survey",
                "verbose_name_plural": "surveys",
            },
        ),
        migrations.AddField(
            model_name="survey",
            name="ordering",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Defines the survey order within the survey selection.",
                verbose_name="choices",
            ),
        ),
    ]
