# Generated by Django 5.2.8 on 2025-11-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0039_alter_survey_options_survey_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={"verbose_name": "survey", "verbose_name_plural": "surveys"},
        ),
        migrations.AlterOrderWithRespectTo(
            name="survey",
            order_with_respect_to="survey_selections",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="ordering",
        ),
    ]
